[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "npm run migrate:all && npm run db:import-seed"
startCommand = "node src/app.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
