-- Tipo ALINEACION_PENDIENTE_SET (notificación a capitanes entre sets)

UPDATE notificaciones
SET categoria = 'TORNEOS'
WHERE categoria IS NULL AND tipo = 'ALINEACION_PENDIENTE_SET';

COMMENT ON COLUMN notificaciones.tipo IS
  'INVITACION_EQUIPO, SOLICITUD_INSCRIPCION, ASIGNACION_ARBITRO, NOMINA_PROPUESTA, ALINEACION_PENDIENTE_SET, RESULTADO_PARTIDO, NUEVO_SEGUIDOR, ETIQUETA_PENDIENTE';
