-- Tipos de notificación para solicitudes de unión a club

COMMENT ON COLUMN notificaciones.tipo IS
  'INVITACION_EQUIPO, SOLICITUD_INSCRIPCION, SOLICITUD_CLUB, CLUB_ACEPTADA, CLUB_RECHAZADA, ASIGNACION_ARBITRO, NOMINA_PROPUESTA, ALINEACION_PENDIENTE_SET, RESULTADO_PARTIDO, NUEVO_SEGUIDOR, ETIQUETA_PENDIENTE';
