export const USER_ACTIVITY_EVENT_TYPES = [
  'RSVP',
  'REACCION',
  'COMENTARIO',
  'VOTO_ENCUESTA',
  'ASISTENCIA_MARCADA',
  'PAGO_REGISTRADO',
  'PUBLICACION_CREADA',
  'INSCRIPCION_TORNEO',
];

export const LAST_ACTIVE_DEBOUNCE_MS = 10 * 60 * 1000;
